import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/layouts/NavBar";
import Footer from "@/components/layouts/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import '@rainbow-me/rainbowkit/styles.css';
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            <Providers>
                <NavBar />
                <div className="p-8">
                    {children}
                </div>
                <Footer />
                <Toaster position="top-center" richColors />
            </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
